config/routes.rb
Happytrials::Application.routes.draw do
  
 
 
 resources :users do
    resources :bottles
  end
  
  resources :bottles do
  
  end
  match 'finduser' => "users#find"
  match "bottles/local/:lat1/:lat2/:long1/:long2/:recent" => "bottles#local"
  match "bottles/local/:lat1/:lat2/:long1/:long2/:recent/:beforetime" => "bottles#localbefore"

    root :to => redirect("/admin_data/quick_search/user")
   

end

app/models/bottle.rb
class Bottle < ActiveRecord::Base
	belongs_to :user
	validates_presence_of :user
	
	def self.recent
	  puts '***recent' 
	  #SAHAR - WORK FROM HERE. 
	  #ALSO- do nearbylocation
  end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :bottles, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  USER_NAME, PASSWORD = "dhh", "secret"
  before_filter :authenticate
  def logged_in?
    true
  end
  private
    def authenticate
      authenticate_or_request_with_http_basic do |user_name, password|
      user_name == USER_NAME && password == PASSWORD
    end
  end    
end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  
  # GET /bottles
  # GET /bottles.xml
  def index
    #@bottles = Bottle.all
    if params[:user_id].nil?
      @bottles = Bottle.all
    else
      @bottles = User.find(params[:user_id]).bottles
    end
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bottles }
			format.json { render :json => @bottles }
    end
  end
  
  def local
    @bottles = Bottle.where(" lat > ? and lat < ? and long > ? and long < ? ",params[:lat1],params[:lat2],params[:long1],params[:long2]).order("time DESC").limit(params[:recent])
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bottles }
			format.json { render :json => @bottles }
    end
  end
  
  def localbefore
    inttime = Integer(params[:beforetime])
	if (inttime > 0)
  	@bottles = Bottle.where(" lat > ? and lat < ? and long > ? and long < ? and time > ? ",params[:lat1],params[:lat2],params[:long1],params[:long2],params[:beforetime]).order("time ASC").limit(params[:recent])  
	else
		@bottles = Bottle.where(" lat > ? and lat < ? and long > ? and long < ? and time < ? ",params[:lat1],params[:lat2],params[:long1],params[:long2],-1 * inttime).order("time DESC").limit(params[:recent])
	end  
    respond_to do |format|
    format.html # index.html.erb
    format.xml  { render :xml => @bottles }
		format.json { render :json => @bottles }
  end
  end
  
  
  def recent
    @bottles = Bottle.recent

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @bottles }
			format.json { render :json => @bottles }
    end
  end
  

  # GET /bottles/1
  # GET /bottles/1.xml
  def show
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @bottle }
    	format.json { render :json => @bottle }
		end
  end

  # GET /bottles/new
  # GET /bottles/new.xml
  def new
    @bottle = Bottle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @bottle }
			format.json { render :json => @bottle }
    end
  end

  # GET /bottles/1/edit
  def edit
    @bottle = Bottle.find(params[:id])
  end

  # POST /bottles
  # POST /bottles.xml
  def create
    @bottle = Bottle.new(params[:bottle])

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to(@bottle, :notice => 'Bottle was successfully created.') }
        format.xml  { render :xml => @bottle, :status => :created, :location => @bottle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /bottles/1
  # PUT /bottles/1.xml
  def update
    @bottle = Bottle.find(params[:id])

    respond_to do |format|
      if @bottle.update_attributes(params[:bottle])
        format.html { redirect_to(@bottle, :notice => 'Bottle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @bottle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1
  # DELETE /bottles/1.xml
  def destroy
    @bottle = Bottle.find(params[:id])
    @bottle.destroy

    respond_to do |format|
      format.html { redirect_to(bottles_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 	def find
    		@users = User.where("email = ?", params[:email]).limit(1)
			#	@users= User.all	
    		respond_to do |format|
          format.html # show.html.erb
          format.xml  { render :xml => @users }
          format.json {render :json => @users}
        end 
      end   
      
      
    
  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
  		format.json {render :json => @users} 
	 end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
			format.json {render :json => @user}
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(@user, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
        format.json { render :json => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
        format.xml  { render :json => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(@user, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bottles/_form.html.erb
<%= form_for(@bottle) do |f| %>
  <% if @bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
      <% @bottle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :emo %><br />
    <%= f.text_field :emo %>
  </div>
  <div class="field">
    <%= f.label :lat %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br />
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :msg %><br />
    <%= f.text_field :msg %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br />
    <%= f.text_field :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bottles/edit.html.erb
<h1>Editing bottle</h1>

<%= render 'form' %>

<%= link_to 'Show', @bottle %> |
<%= link_to 'Back', bottles_path %>

app/views/bottles/index.html.erb
<h1>Listing bottles</h1>

<table>
  <tr>
    <th>Emo</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Msg</th>
    <th>User_id</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bottles.each do |bottle| %>
  <tr>
    <td><%= bottle.emo %></td>
    <td><%= bottle.lat %></td>
    <td><%= bottle.long %></td>
    <td><%= bottle.msg %></td>
    <td><%= bottle.user_id %></td>
    <td><%= bottle.time %></td>
    <td><%= link_to 'Show', bottle %></td>
    <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
    <td><%= link_to 'Destroy', bottle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Bottle', new_bottle_path %>

app/views/bottles/local.html.erb
<p>LOCAL</p>


<table>
  <tr>
    <th>Emo</th>
    <th>Lat</th>
    <th>Long</th>
    <th>Msg</th>
    <th>User_id</th>
    <th>Time</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bottles.each do |bottle| %>
  <tr>
    <td><%= bottle.emo %></td>
    <td><%= bottle.lat %></td>
    <td><%= bottle.long %></td>
    <td><%= bottle.msg %></td>
    <td><%= bottle.user_id %></td>
    <td><%= bottle.time %></td>
    <td><%= link_to 'Show', bottle %></td>
    <td><%= link_to 'Edit', edit_bottle_path(bottle) %></td>
    <td><%= link_to 'Destroy', bottle, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

app/views/bottles/new.html.erb
<h1>New bottle</h1>

<%= render 'form' %>

<%= link_to 'Back', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Emo:</b>
  <%= @bottle.emo %>
</p>

<p>
  <b>Lat:</b>
  <%= @bottle.lat %>
</p>

<p>
  <b>Long:</b>
  <%= @bottle.long %>
</p>

<p>
  <b>Msg:</b>
  <%= @bottle.msg %>
</p>

<p>
  <b>User_id:</b>
  <%= @bottle.user_id %>
</p>

<p>
  <b>Time:</b>
  <%= @bottle.time %>
</p>


<%= link_to 'Edit', edit_bottle_path(@bottle) %> |
<%= link_to 'Back', bottles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyTrack</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.email %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Email:</b>
  <%= @user.email %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>